Added grammar meanings to the words
jProgr/buku-name pull request #1
Opened 2023-07-01 12:17 UTC by muhdsalm

This commit simply adds grammar meanings to the words that have grammar meanings, such as 'ke' also introducing subordinate clauses.

Also two more small things:
- Added 'out of' and 'made of' to the meaning of 'de'
- Added an example to 'a', 'Bob a man', to show that a can be used as 'is' for nouns.

2023-07-01 15:55 UTC, jProgr requested changes
Thank you very much!

2023-07-01 15:55 UTC, jProgr commented on src/data/base_mini_dictionary.csv
> +ave;have, possession, [grammar] perfect tense
I don't think a new syntax is needed. We can just use "marks perfect tense".

2023-07-01 15:55 UTC, jProgr commented on src/data/base_mini_dictionary.csv
> +de;from, of, about, by, out of, made of, [grammer] past tense
"marks past tense"

2023-07-01 15:55 UTC, jProgr commented on src/data/base_mini_dictionary.csv
> +en;in, at, on, [grammar] progressive tense
"marks progressives tense".

2023-07-01 15:55 UTC, jProgr commented on src/data/base_mini_dictionary.csv
> +go;to, go, towards, for [grammer] future
"marks future tense"

2023-07-01 15:55 UTC, jProgr commented on src/data/base_mini_dictionary.csv
> +ke;what, that, [grammer] introduce dependant clause
"introduces dependant clause"

2023-07-01 15:55 UTC, jProgr commented on src/data/base_mini_dictionary.csv
> +lase;let, allow, license, permission, licit, [grammar] hortative mood
"marks hortative mood"

2023-07-01 15:55 UTC, jProgr commented on src/data/base_mini_dictionary.csv
> +pasa;pass, happen, past, [grammar] habitual tense
"marks habitual mood".

2023-07-01 15:55 UTC, jProgr commented on src/data/mini_dictionary.csv
Same observations as with `base_mini_dictionary.csv`.

2023-07-01 15:55 UTC, jProgr commented on src/data/mini_dictionary.csv
> -Australia;Australia
Why?

2023-07-02 07:30 UTC, muhdsalm commented
I have fixed all the problems you pointed out. If there's any other problems, let me know!

2023-07-02 17:13 UTC, jProgr commented
@muhdsalm Thank you very much.

Finally, to merge your changes I need you to answer this: Are you aware and agree that your changes will be on the public domain? https://github.com/jProgr/buku-name/blob/master/LICENSE.md

2023-07-02 18:49 UTC, muhdsalm commented
I am aware and I agree.

2023-07-03 02:18 UTC, merged

2023-07-03 02:18 UTC, jProgr commented
Thank you very much, your changes have been merged.